version: '3'

services:
  mysql:
    image: bitnami/mysql:latest
    ports:
      - 10140:3306
    environment:
      MYSQL_ROOT_PASSWORD: "1q2w3e4R5t#"
      MYSQL_DATABASE: "app"
      MYSQL_USER: "guest"
      MYSQL_PASSWORD: "1q2w3e4r5t"
      MYSQL_AUTHENTICATION_PLUGIN: "mysql_native_password"
      
    volumes:
      #- ./docker/mysql/custom.cnf:/etc/mysql/conf.d/custom.cnf
      - ./data/mysql:/bitnami/mysql/data
    networks:
      - backend

  redis:
    image: bitnami/redis:latest
    ports:
      - 6379:6379
    environment:
      ALLOW_EMPTY_PASSWORD: "yes"
    networks:
      - backend

  hub-chrome:
    #image: selenium/node-chrome:beta
    image: seleniarm/node-chromium:latest
    shm_size: 2gb
    depends_on:
      - hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443

  hub:
    image: seleniarm/hub:latest
    container_name: selenium-hub
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"
networks:
  backend:
    external: true