version: '3'

services:
  mysql:
    image: bitnami/mysql:latest
    ports:
      - 10140:3306
    environment:
      MYSQL_ROOT_PASSWORD: "1q2w3e4R5t#"
      MYSQL_DATABASE: "app"
      MYSQL_USER: "guest"
      MYSQL_PASSWORD: "1q2w3e4r5t"
      MYSQL_AUTHENTICATION_PLUGIN: "mysql_native_password"
      
    volumes:
      #- ./docker/mysql/custom.cnf:/etc/mysql/conf.d/custom.cnf
      - ./data/mysql:/bitnami/mysql/data
    networks:
      - backend

  #redis:
  # image: bitnami/redis:latest
  #  ports:
  #    - 6379:6379
  #  environment:
  #    ALLOW_EMPTY_PASSWORD: "yes"
  #  networks:
  #    - backend
networks:
  backend:
    external: true